/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Depositor } from "./Depositor";
export type { RewardManager } from "./RewardManager";
export type { RewardPool } from "./RewardPool";
export type { StakingDatabase } from "./StakingDatabase";
export type { StakingManager } from "./StakingManager";
export type { VirtuaStaking } from "./VirtuaStaking";

export { Depositor__factory } from "./factories/Depositor__factory";
export { RewardManager__factory } from "./factories/RewardManager__factory";
export { RewardPool__factory } from "./factories/RewardPool__factory";
export { StakingDatabase__factory } from "./factories/StakingDatabase__factory";
export { StakingManager__factory } from "./factories/StakingManager__factory";
export { VirtuaStaking__factory } from "./factories/VirtuaStaking__factory";
